name: zoned_line_chart_example
description: Example app demonstrating the zoned_line_chart package.

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  zoned_line_chart:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.1.0
